name: Build and Deploy to ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  ACR_NAME: group4acr
  ACR_LOGIN_SERVER: group4acr.azurecr.io
  RG: RG-group4
  VMSS_BE: vmss-backend-group4
  VMSS_FE: vmss-frontend-group4
  APP_DIR: /home/azureuser/ecommerce-app-three-tier-azure-db-ih

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name "$ACR_NAME"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build & push backend
      - name: Build and Push Backend
        run: |
          set -euo pipefail
          BACKEND_TAG=${{ github.sha }}
          docker build -t $ACR_LOGIN_SERVER/ecommerce-backend:${BACKEND_TAG} ./ecommerce-app-backend
          docker tag $ACR_LOGIN_SERVER/ecommerce-backend:${BACKEND_TAG} $ACR_LOGIN_SERVER/ecommerce-backend:latest
          docker push $ACR_LOGIN_SERVER/ecommerce-backend:${BACKEND_TAG}
          docker push $ACR_LOGIN_SERVER/ecommerce-backend:latest

      # Build & push frontend
      - name: Build and Push Frontend
        run: |
          set -euo pipefail
          FRONTEND_TAG=${{ github.sha }}
          docker build -t $ACR_LOGIN_SERVER/ecommerce-frontend:${FRONTEND_TAG} ./ecommerce-app-frontend
          docker tag $ACR_LOGIN_SERVER/ecommerce-frontend:${FRONTEND_TAG} $ACR_LOGIN_SERVER/ecommerce-frontend:latest
          docker push $ACR_LOGIN_SERVER/ecommerce-frontend:${FRONTEND_TAG}
          docker push $ACR_LOGIN_SERVER/ecommerce-frontend:latest

      # ===== Loop لكل إنستانس في Backend VMSS =====
      - name: Update VMSS Backend (loop all instances)
        shell: bash
        run: |
          set -euo pipefail
          IDS=$(az vmss list-instances -g "$RG" -n "$VMSS_BE" --query "[].instanceId" -o tsv)
          if [ -z "${IDS}" ]; then
            echo "No instances found in $VMSS_BE — skipping."
            exit 0
          fi
          for id in $IDS; do
            echo "Updating $VMSS_BE instance $id ..."
            az vmss run-command invoke \
              -g "$RG" -n "$VMSS_BE" \
              --command-id RunShellScript \
              --instance-id "$id" \
              --scripts '
                set -e
                cd '"$APP_DIR"'
                az login --identity
                TOKEN=$(az acr login --name '"$ACR_NAME"' --expose-token --query accessToken -o tsv)
                echo $TOKEN | docker login '"$ACR_LOGIN_SERVER"' -u 00000000-0000-0000-0000-000000000000 --password-stdin
                docker compose pull backend
                docker compose up -d --no-deps backend
                docker image prune -f
              ' > /dev/null
          done

      # ===== Loop لكل إنستانس في Frontend VMSS =====
      - name: Update VMSS Frontend (loop all instances)
        shell: bash
        run: |
          set -euo pipefail
          IDS=$(az vmss list-instances -g "$RG" -n "$VMSS_FE" --query "[].instanceId" -o tsv)
          if [ -z "${IDS}" ]; then
            echo "No instances found in $VMSS_FE — skipping."
            exit 0
          fi
          for id in $IDS; do
            echo "Updating $VMSS_FE instance $id ..."
            az vmss run-command invoke \
              -g "$RG" -n "$VMSS_FE" \
              --command-id RunShellScript \
              --instance-id "$id" \
              --scripts '
                set -e
                cd '"$APP_DIR"'
                az login --identity
                TOKEN=$(az acr login --name '"$ACR_NAME"' --expose-token --query accessToken -o tsv)
                echo $TOKEN | docker login '"$ACR_LOGIN_SERVER"' -u 00000000-0000-0000-0000-000000000000 --password-stdin
                docker compose pull frontend
                docker compose up -d --no-deps frontend
                docker image prune -f
              ' > /dev/null
          done
