name: Build and Deploy to ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  ACR_NAME: group4acr
  ACR_LOGIN_SERVER: group4acr.azurecr.io
  RG: RG-group4
  VMSS_BE: vmss-backend-group4
  VMSS_FE: vmss-frontend-group4
  APP_DIR: /home/azureuser/ecommerce-app-three-tier-azure-db-ih

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1) Checkout
      - uses: actions/checkout@v4

      # 2) Azure login (سكريت واحد: AZURE_CREDENTIALS)
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3) ACR login (تأكد أن الـ SP يملك AcrPush)
      - name: ACR Login
        run: az acr login --name "$ACR_NAME" --only-show-errors

      # 4) Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # (اختياري لكن مفيد) اكتب نسخة الواجهة في public/version.txt لظهورها بعد البناء
      - name: Prepare frontend version file
        run: echo "${{ github.sha }}" > ./ecommerce-app-frontend/public/version.txt

      # 5) Build & push Backend
      - name: Build and Push Backend
        run: |
          set -euo pipefail
          TAG=${{ github.sha }}
          docker build \
            -t $ACR_LOGIN_SERVER/ecommerce-backend:${TAG} \
            -t $ACR_LOGIN_SERVER/ecommerce-backend:latest \
            ./ecommerce-app-backend
          docker push $ACR_LOGIN_SERVER/ecommerce-backend:${TAG}
          docker push $ACR_LOGIN_SERVER/ecommerce-backend:latest

      # 6) Build & push Frontend
      - name: Build and Push Frontend
        run: |
          set -euo pipefail
          TAG=${{ github.sha }}
          docker build \
            -t $ACR_LOGIN_SERVER/ecommerce-frontend:${TAG} \
            -t $ACR_LOGIN_SERVER/ecommerce-frontend:latest \
            ./ecommerce-app-frontend
          docker push $ACR_LOGIN_SERVER/ecommerce-frontend:${TAG}
          docker push $ACR_LOGIN_SERVER/ecommerce-frontend:latest

      # 7) حدّث كل إنستانس Backend باستخدام instance-id (أرقام)
      - name: Update VMSS Backend (loop all instances by instance-id)
        shell: bash
        run: |
          set -euo pipefail
          IDS=$(az vmss list-instances -g "$RG" -n "$VMSS_BE" --query "[].instanceId" -o tsv)
          if [ -z "${IDS}" ]; then
            echo "No backend instances found — skipping."
            exit 0
          fi
          for ID in $IDS; do
            echo "Updating backend instanceId=$ID ..."
            az vmss run-command invoke \
              -g "$RG" -n "$VMSS_BE" \
              --instance-id "$ID" \
              --command-id RunShellScript \
              --scripts '
                set -e
                cd '"$APP_DIR"'
                az login --identity
                TOKEN=$(az acr login --name '"$ACR_NAME"' --expose-token --query accessToken -o tsv)
                echo $TOKEN | docker login '"$ACR_LOGIN_SERVER"' -u 00000000-0000-0000-0000-000000000000 --password-stdin
                docker compose pull backend
                docker compose up -d --no-deps --pull always --force-recreate backend
                docker ps --filter name=ecommerce-backend --format "container={{.ID}} image={{.Image}}"
                docker image ls '"$ACR_LOGIN_SERVER"'/ecommerce-backend --digests
                docker image prune -f
              ' >/dev/null
          done

      # 8) حدّث كل إنستانس Frontend بالطريقة نفسها
      - name: Update VMSS Frontend (loop all instances by instance-id)
        shell: bash
        run: |
          set -euo pipefail
          IDS=$(az vmss list-instances -g "$RG" -n "$VMSS_FE" --query "[].instanceId" -o tsv)
          if [ -z "${IDS}" ]; then
            echo "No frontend instances found — skipping."
            exit 0
          fi
          for ID in $IDS; do
            echo "Updating frontend instanceId=$ID ..."
            az vmss run-command invoke \
              -g "$RG" -n "$VMSS_FE" \
              --instance-id "$ID" \
              --command-id RunShellScript \
              --scripts '
                set -e
                cd '"$APP_DIR"'
                az login --identity
                TOKEN=$(az acr login --name '"$ACR_NAME"' --expose-token --query accessToken -o tsv)
                echo $TOKEN | docker login '"$ACR_LOGIN_SERVER"' -u 00000000-0000-0000-0000-000000000000 --password-stdin
                docker compose pull frontend
                docker compose up -d --no-deps --pull always --force-recreate frontend
                docker ps --filter name=ecommerce-frontend --format "container={{.ID}} image={{.Image}}"
                docker image ls '"$ACR_LOGIN_SERVER"'/ecommerce-frontend --digests
                curl -sS http://127.0.0.1:3000/version.txt || true
                docker image prune -f
              ' >/dev/null
          done
